repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^deployments/new-deployment/
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--ignore-words", ".codespell-ignore"]
        exclude: >
          (?x)^(
            .*\.html|
          )$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy
        args: [--config-file=mypy.ini]
        additional_dependencies: [
          numpy==2.3.3,
          "rossum-api @ git+https://github.com/stancld/rossum-api.git@ds-feat-schema-content",
          types-seaborn==0.13.2.20250914,
          types-requests==2.32.4.20250913
        ]
        language: python
        pass_filenames: false
        types: [python]
