---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: rossum-agent
  labels:
    app.kubernetes.io/component: agent-ui

spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: agent-ui
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: agent-ui
      annotations:
        scheduling.rossum.ai/disruption-cost-seconds: '20'
    spec:
      serviceAccountName: rossum-agent
      containers:
        - envFrom:
            - configMapRef:
                name: rossum-agent
            - secretRef:
                name: rossum-agent
          image: app-image
          imagePullPolicy: Always
          name: rossum-agent
          command: ["uv", "run", "streamlit", "run", "rossum_agent/app.py"]
          args:
            - --server.headless=true
            - --server.enableCORS=false
            - --server.enableXsrfProtection=true
          ports:
            - containerPort: 8501
              name: http
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 2Gi
