---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - externalsecret.yaml

configMapGenerator:
  - name: rossum-agent
    literals:
      - REGION_NAME=${AWS_REGION:-us-east-1}
      - AWS_REGION=${AWS_REGION:-us-east-1}
