---
apiVersion: v1
kind: Service

metadata:
  name: rossum-agent

spec:
  selector:
    app.kubernetes.io/component: agent-ui
  ports:
    - name: http
      port: 8501
      protocol: TCP
      targetPort: 8501
  type: ClusterIP
